#!/bin/sh
set -e

PKG="polymutt"
VER="0.13"
PKG_DIR=/usr/lib/${PKG}${VER}
TEST_EXE=polymutt

if [ \( "$1" = "upgrade" -o "$1" = "remove" \) -a -L /usr/bin/${TEST_EXE} ]; then
    for pathname in ${PKG_DIR}/bin/*; do
        filename=`basename $pathname`
        update-alternatives --remove ${filename} /usr/bin/${filename}${VER}
    done
fi

